name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./Security/Security.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Parasoft C/C++test
      uses: parasoft/run-cpptest-action@1.0.1
      with:
        input: './Security/Security.sln'
        testConfig: 'builtin://CWE Top 25 + On the Cusp 2019'
        reportFormat: 'sarif'
        commandLinePattern: '"C:/Program Files (x86)/Parasoft/C++test for Visual Studio/10.5/cpptestcli.exe" -config "${testConfig}" -solution "${input}" -report "${reportDir}" -property report.format=${reportFormat} -nobuild'

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/report.sarif
        
