name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./Security/Security.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run Parasoft C/C++test
      uses: parasoft/run-cpptest-action@1.0.1
      with:
        input: './VS2019/VS2019/Security/Security.sln'
        testConfig: 'builtin://CWE Top 25 + On the Cusp 2019'
        commandLinePattern: '${cpptestcli} -config "${testConfig}" -solution "${input}" -report "${reportDir}" -nobuild'
